---
title: "Assignment 3"
author: "Hitanshu Prajapati"
date: "08-16-2022"
output: html_document
---


## Introduction

This data set contains information about incarcerations in all the counties in America. The data has 153,811 observations and 121 columns of different kinds of information such as the the jail populations of different races in each county. The columns related to this are what I will be focusing on analyzing in my report. Specifically, the variables I chose to analyze are aapi_jail_pop, black_jail_pop, latinx_jail_pop, native_jail_pop, white_jail_pop, other_race_jail_pop, black_jail_pop_rate, white_jail_pop_rate. These variables contain information on the jail population, in each county, of many races including Asian American/Pacific Islander, Black, Latinx, Native American, White, and other races and also the rates of incarceration over the years of the Black and White populations. By looking at these variables I will be focusing my analysis on comparing incarceration rates and populations of different racial groups to identify patterns of racism.

## Summary Information

Using the information provided in the incarcerations data set I was able to analyze the differences between the jail populations of multiple races and the differences between the jail population rates of multiple races. One thing that was surprising to me as a result of my analysis was that the jail population comparisons and the jail population rates comparisons were contradicting each other. To compare the jail populations of different states in a specified year, I filtered the data set for that year and then took a sum of the jail population column for each race. When I ran this function for the year 2018, the result I got was that incarcerations were highest for the white population at 346,062. In comparison to the black population, which had 247,547 incarcerations, the white population had about 100,000 more incarcerations. The same pattern was seen when I calculated the total populations for the year 1985 when 86,947 black people were incarcerated and 89,248 white people were jailed. Again, white people were incarcerated the most. Looking at just this information it seems that racial injustice doesn't seem to be a problem in the prison system. However, a comparison of the rates of jail populations in America tells a different story. When comparing the average incarceration rate of the counties in the year 2018, the black population rate is 2519 and the white population rate is 498. In the year 1990, the black population rate is 4041 and the white population rate is 145. From these values it is clear that black people are being jailed at a significantly higher rate than white people. Although the difference between the jailing rates of the two races has decreased, it is still significantly high, suggesting that there is still racism in the prison system.

## Trends Over Time


## Variable Comparison


## Map